spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.152:3306/mqtt-basedata?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  main:
    allow-circular-references: true
mqtt:
  username: emqx                      #账号
  password: public                 #密码
  hosturl: tcp://192.168.10.236:1883              #mqtt地址
  clientId: S&D106EOB5V2YI&19&afaf           #客户端ID 不可重复
  default-topic: test                        # 默认主题
  timeout: 60                                # 超时时间
  keepalive: 60                              # 保持连接
  clearSession: true                         # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)
  maxInflight: 1000


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: logs/log.log # 日志文件地址
  level:
    '[com.epower]': debug
    '[org.springframework.web]': debug
  logback:
    rollingpolicy:
      max-history: 7
server:
  port: 8943
